### ISSUE TITLE
Laravel 8.0 incompatibility

### ISSUE THREAD

**Issue by danniehansen** [kunalvarma05/dropbox-php-sdk#174]
Laravel 8.0 upgrade guide specify a guzzle ^7.0.1 requirement that is not met by dropbox-php-sdk https://laravel.com/docs/8.x/upgrade

Is there any plans for guzzle 7.0 support?

**Comment by danielriosantos** [comment]
+1

**Comment by slightlydiff** [comment]
Thanks for you email.

I'm away until Monday 12th October.  

For any hosting support issues please submit a ticket via https://my.slightlydifferent.co.nz/submitticket.php

For all other matters please raise a ticket if urgent only. Otherwise I will get back to you as soon as possible on my return.

Kind regards

Steve

**Comment by m-dl** [comment]
+1 please update it, it's urgent

**Comment by maierwalter** [comment]
+1 please let me know if I can help somehow

**Comment by VictorPullzz** [comment]
+1 Please add support guzzle v7 and this fix our problem

**Comment by fflone** [comment]
+1 This update would be great
