### ISSUE TITLE
Problems with uploadChunked

### ISSUE THREAD

**Issue by david63** [kunalvarma05/dropbox-php-sdk#2]
Whenever I try to use $dropbox->upload or $dropbox->uploadChunked I am getting incorrect offset errors

DropboxClientException in DropboxGuzzleHttpClient.php line 67: {"error_summary": "lookup_failed/incorrect_offset/..", "error": {".tag": "lookup_failed", "lookup_failed": {".tag": "incorrect_offset", "correct_offset": 12556930}}}

I should add the using $dropbox->simpleUpload works without any problem when uploading the same file.

**Comment by kunalvarma05** [comment]
This should most probably be due to a chunk being uploaded with an incorrect offset. Let me check.

**Comment by kunalvarma05** [comment]
I tried the `$dropbox->upload` method on all types of files, works fine. However, trying to upload really small files using `$dropbox->uploadChunked` gave the `incorrect_offset` error.

The `upload` method calls the `uploadChunked` method if the file size exceeds ~8 MB. Can you tell me the type and size of the file you tried uploading?

Thanks!

**Comment by david63** [comment]
The file was about 8.4mb

**Comment by compujosh** [comment]
Same issue using upload() with a .tar.gz file with size ~54MB

**Comment by kunalvarma05** [comment]
Let me see if I can reproduce the bug and figure out what's causing it. 

Thanks.

**Comment by compujosh** [comment]
The full error message is 

> Fatal error: Uncaught Kunnu\Dropbox\Exceptions\DropboxClientException: {"error_summary": "incorrect_offset/...", "error": {".tag": "incorrect_offset", "correct_offset": 60073809}} in C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Http\Clients\DropboxGuzzleHttpClient.php:67 Stack trace: #0 C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\DropboxClient.php(155): Kunnu\Dropbox\Http\Clients\DropboxGuzzleHttpClient->send('https://content...', 'POST', '', Array) #1 C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox.php(250): Kunnu\Dropbox\DropboxClient->sendRequest(Object(Kunnu\Dropbox\DropboxRequest)) #2 C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox.php(278): Kunnu\Dropbox\Dropbox->sendRequest('POST', '/files/upload_s...', 'content', Array, 'WkDix9e7h8wAAAA...') #3 C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Dropbox. in C:\XAMPP\htdocs\inventory\inc\Composer\vendor\kunalvarma05\dropbox-php-sdk\src\Dropbox\Http\Clients\DropboxGuzzleHttpClient.php on line 67

and here's the code snippet:

```
[...]
require_once(COMPOSER_DIR."/autoload.php");

use Kunnu\Dropbox\Dropbox;
use Kunnu\Dropbox\DropboxApp;

if (isset($config['dropbox']['appKey'])) {
	$start_time = microtime(true);

	$dropbox_app = new DropboxApp($config['dropbox']['appKey'], $config['dropbox']['appSecret'], $config['dropbox']['accessToken']);
	$dropbox = new Dropbox($dropbox_app);

	$file = $dropbox->upload($fileBackup, '/Dropbox/InventoryManagerBackups/daily/files/'.basename($fileBackup), ['autorename' => true]);

	//Uploaded File
	//print_r($file);

	$file = $dropbox->upload($sqlBackup, '/Dropbox/InventoryManagerBackups/daily/sql/'.basename($sqlBackup), ['autorename' => true]);

	echo microtime(true)-$start_time;
}
else {
	echo "Fatal error: No dropbox config set in config.ini";
}
```

**Comment by compujosh** [comment]
I added debug code in uploadChunked() in Dropbox.php

```
        while ($remaining > $chunkSize) {
            echo "Uploaded: ".$uploaded." Remaining:".$remaining."<br/>";
            //Append the next chunk to the Upload session
            $sessionId = $this->appendUploadSession($dropboxFile, $sessionId, $uploaded, $chunkSize);

            //Update remaining and uploaded
            $uploaded += $chunkSize;
            $remaining -= $chunkSize;
        }

        echo "--Final Chunk-- Uploaded: ".$uploaded." Remaining:".$remaining."<br/>";

        //Finish the Upload Session and return the Uploaded File Metadata
        return $this->finishUploadSession($dropboxFile, $sessionId, $uploaded, $remaining, $path);
```

Results:

> Uploaded: 4000000 Remaining:52073809
> Uploaded: 8000000 Remaining:48073809
> 
> Fatal error: Uncaught Kunnu\Dropbox\Exceptions\DropboxClientException: {"error_summary": "incorrect_offset/...", "error": {".tag": "incorrect_offset", "correct_offset": 60073809}}

So it uploads the first chunk, enters the while loop, and tries and fails to upload the second chunk I think

**Comment by kunalvarma05** [comment]
Fixed!

The problem was within the [`makeDropboxFile()`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L306) method inside the [`Dropbox`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php) class. This method makes a [`DropboxFile`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxFile.php) object with another DropboxFile object or path to a file, the `maxLength` and `offset` params, respectively.

According to the following [**line**](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L313), when a path to a file is passed, it sets the `maxLength` and `offset` params in the DropboxFile [**constructor**](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/DropboxFile.php#L50) correctly.

However, when a DropboxFile object was passed to the `makeDropboxFile()` method, in this case while calling the [`appendUploadSession`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L999) inside the [`uploadChunked`](https://github.com/kunalvarma05/dropbox-php-sdk/blob/master/src/Dropbox/Dropbox.php#L960) method, the `makeDropboxFile()` method failed to set the `maxLength` and `offset` properties on the DropboxFile object.

[**This commit**](https://github.com/kunalvarma05/dropbox-php-sdk/commit/f3c8129ebb199aa4ea430ed93477b55b2b5dc2be) fixes the issue.

Give it a shot and let me know.

Thanks @david63 for reporting the issue and @compujosh for helping to debug.

Cheers!

**Comment by david63** [comment]
Just tested the latest version with the original file and it appears to be working OK - thanks

**Comment by compujosh** [comment]
Seems to be working, however it still takes a lot longer than simpleUpload()
