### ISSUE TITLE
mcrypt deprecated in php 7.1

### ISSUE THREAD

**Issue by sharksoft** [kunalvarma05/dropbox-php-sdk#29]
Hi,
on ubuntu 14.04 with php7.1

<b>Deprecated</b>:  Function mcrypt_create_iv() is deprecated in <b>/var/www/html/abbashare/vendor/kunalvarma05/dropbox-php-sdk/src/Dropbox/Security/McryptRandomStringGenerator.php</b> on line 47

From php.net:
The Mcrypt library has been declared DEPRECATED since PHP 7.1, to use in its OpenSSL

**Comment by kunalvarma05** [comment]
Hey,

I'm working on a PHP7+ only version of the package.

For now, instead of the `Kunnu/Dropbox/Security/McryptRandomStringGenerator`, you can use the `Kunnu/Dropbox/Security/OpenSslRandomStringGenerator` class. 

This can be done while initializing the `Dropbox` class. You can follow the  [Advanced Configuration](../wiki/Advanced-Configuration#random-string-generator) guide which shows how you can swap the default `McryptRandomStringGenerator` with the `OpenSslRandomStringGenerator` or with your own implementation of the [RandomStringGeneratorInterface](../blob/master/src/Dropbox/Security/RandomStringGeneratorInterface.php).

Thanks for reporting :)

**Comment by Spreeuw** [comment]
Perhaps add a fallback to `random_bytes()` in case ext/openssl is not installed?
