### ISSUE TITLE
Can't sort listFolder result

### ISSUE THREAD

**Issue by andreaPress** [kunalvarma05/dropbox-php-sdk#36]
Hi,
thank you very much for this great SDK, I've found it very useful ;)
I've a little problem with the sortBy() method of Laravel Collections.

```
$params['recursive'] = false;
$params['include_media_info'] = true;
$content= $dropbox->listFolder("/folder", $params);
$items = $content->getItems();
$itemsSorted = $items->sortBy('name');
```

But they don't seem to be sorted by name....
Any suggestion will be very appreciated.
Thanks!!

**Comment by code-sallo** [comment]
I write me for this a sort function. Comments are in german, sorry.

`private function item_sort($a, $b) {
	$a_name = $a->getName();
	$a_dir = $this->is_dir($a);
	$b_name = $b->getName();
	$b_dir = $this->is_dir($b);

	// Nur A ist Verzeichnis
	if ($a_dir and !$b_dir) {
		return -1;
	}
	// Nur B ist Verzeichnis
	else if (!$a_dir and $b_dir) {
		return 1;
	}
	// Beides Verzeichnis oder Datei
	else if ($a_name == $b_name) {
		return 0;
	}
	// A muss vor B stehen
	else if ($a_name < $b_name) {
		retuen -1;
	}
	// B muss vor A stehen
	else {
		return 1;
	}
}`

I put all my items in an array, otherwise I get an error.

`$items = $metadata->getItems();

// Items zum Sortieren in Array schreiben
$aItems = array();
foreach ($items as $i) {
	array_push($aItems, $i);
}
usort($items, array($this, "item_sort"));`

**Comment by kunalvarma05** [comment]
@andreaPress This should do the job:

```php
$itemsSorted = $items->sortBy(function ($item, $key) {
    return ord(strtolower($item->getName()));
});
```
**See**
Collection [`sortBy`](https://laravel.com/docs/collections#method-sortby) method.
PHP [`ord()`](http://php.net/manual/en/function.ord.php) function.
