### ISSUE TITLE
Get web path of the item?

### ISSUE THREAD

**Issue by taat** [kunalvarma05/dropbox-php-sdk#65]
Is there a way I can get dropbox web interface path to a certain folder?  
Eg. /my/folder -> https://dropbox.com/sh/yax0nfulawyfra5/ABBbXn-9hcEKWX6h8NdXxIzra?dl=0

**Comment by nofont** [comment]
Those URLs are in the shared link metadata endpoint. 

Without deeper insight into this SDK I would say no, you cannot currently get them since "Shared links and Shared Folder" are listed as _coming soon_.

**Comment by gety9** [comment]
@nofont 

Could you explain what is the difference between OP issue and these 2:
https://github.com/kunalvarma05/dropbox-php-sdk/issues/32
https://github.com/kunalvarma05/dropbox-php-sdk/issues/1

"Shared links and Shared Folder" are indeed listed as coming soon, but in above issues they use share functionality.

I guess there is the difference between "Shared links and Shared Folder" and create_shared_link_with_settings used as solutions in above issues.

**Comment by kunalvarma05** [comment]
@gety9 You can work with all the endpoints documented on the [Dropbox's Developer site](https://www.dropbox.com/developers/documentation/http/documentation) through the SDK. 

What I mean by "Shared links and Shared Folder are coming soon" is that the SDK doesn't have dedicated methods for interacting with the sharing endpoints, similar to how you have dedicated methods to **[get metadata of files/folders](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Working-with-files#get-filefolder-metadata)** or **[upload a file](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Upload-and-Download-Files#auto-file-upload)**. However, the SDK can still make requests to the sharing endpoints (or any Dropbox API endpoint) and fetch/decode data.

For example:

**Using the dedicated method**
```php
/**
* Assuming you have configured the DropboxApp class
* @see https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Configuration
*/
$dropbox = new Dropbox($app);

$path = "/hello.txt";

//Get File Metadata
$metadata = $dropbox->getMetadata($path)

$metadata->getName();
```

**Using the generic method**
```php
/**
* Assuming you have configured the DropboxApp class
* @see https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Configuration
*/
$dropbox = new Dropbox($app);

$path = "/hello.txt";


//Get File Metadata
$response = $dropbox->postToAPI('/files/get_metadata', [
    'path' => $path
]);

// Get the Decoded Body
$body = $response->getDecodedBody();

$metadata = new FileMetadata($body);

$metadata->getName();
```

You can achieve the same result, as the Dedicated Method, through the Generic method. This generic method is used internally by the dedicated method. Thus, a dedicated method is simply a wrapper over the generic method.

I guess, it would be better to have this code snippet be inserted instead of the "Shared links and Shared Folder are coming soon" message.

**Comment by kunalvarma05** [comment]
@taat Take a look at **issue #66**.

You can use the [Create Shared Link with Settings](https://www.dropbox.com/developers/documentation/http/documentation#sharing-create_shared_link_with_settings) endpoint to fetch a shareable link of a file or folder.
