### ISSUE TITLE
Why client_id and client_secret are required parameters?

### ISSUE THREAD

**Issue by idubinets** [kunalvarma05/dropbox-php-sdk#69]
I already have access token, so that client_id and client_secret should not be required arguments, but no.
The library still requires it. why?

**Comment by kunalvarma05** [comment]
It's required for obtaining the Access Token. Since the SDK supports Authorization out of the box, the client ID and Secret *arguments* are required for creating an instance of the DropboxApp class which is used by the Dropbox service class.

If you already have it, you can simply pass in empty strings instead of the client ID and secret to the DropboxApp class.
