### ISSUE TITLE
Minimum PHP version requirements? 

### ISSUE THREAD

**Issue by katmoody** [kunalvarma05/dropbox-php-sdk#92]
Hi there - 

We are looking into whether using this option would be a viable one for us to replace the older SDK we were using, but the PHP version minimum means it will preclude many of our current users in their current server setups. Do you know what functionality is tied to the minimum php version you have in the wiki (5.6.4)? 

I looked back through other issues and did see that Guzzle is tied to a slightly lower version of php, but not what would specify the need for v 5.6.4.

**Comment by kunalvarma05** [comment]
Guzzle `~6.0`, which the SDK uses, requires [PHP version >=5.5.0](https://github.com/guzzle/guzzle/blob/6.0.0/composer.json#L16). 

I'm aware that the Wiki section lists the minimum PHP version required is `5.6.40` or greater. Which was due to the [Collection package](https://github.com/tightenco/collect/blob/v5.3.23/composer.json#L13), which the SDK uses, and not Guzzle. 

And for the above issue, we already have a discussion going on. **See issue #90**.

What is the minimum version you're looking for the SDK to support?

**Comment by katmoody** [comment]
Hey there - I think we're going to end up going with a custom solution, but we're also playing with this SDK still ;-) 

Many of our users are still at PHP 5.3, which was our previous minimum version. We hate to force them to upgrade further unless we don't have another choice :D - we're still working on it though! 

Thanks so much for replying and sorry I was delayed in getting back with you!

**Comment by kunalvarma05** [comment]
By making some adjustments and configurations to the SDK, you can get a custom solution that supports PHP 5.3. The **[Advanced Configuration guide](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Advanced-Configuration)** might come in handy.

Godspeed!
