### ISSUE TITLE
n00b question

### ISSUE THREAD

**Issue by jiska78** [kunalvarma05/dropbox-php-sdk#98]
Sorry, I'm just a hack trying to upload a database backup to dropbox. API v1 worked fine but now I'm forced to migrate.

Here's the code I used to use, with the old API v1 commands and the new API v2 ones.

Not working - can someone please help?

use Dropbox\Dropbox;
use Dropbox\DropboxApp;
use Dropbox\DropboxFile;

$app = new DropboxApp(1,2,3);
$dropbox = new Dropbox($app);

$backupFile = "/home/edplorga/backups/temp/db_" . date('d-m-Y').".zip";
$backupFilename = "/db_" . date('d-m-Y').".zip";

//Old stuff
$appInfo = dbx\AppInfo::loadFromJsonFile(__DIR__."/config.json");
$dbxClient = new dbx\Client($accessToken, "EDPL_SQL_Backups");
$f = fopen($backupFile, "rb");
$result = $dbxClient->uploadFile($backupFilename, dbx\WriteMode::force(), $f);
fclose($f);

//New stuff
$dropboxFile = DropboxFile::createByStream($backupFilename, $backupFile);

**Comment by kunalvarma05** [comment]
You're correct till the: "creating a `DropboxFile` instance" part. Now you need to pass this instance to the `upload()` method in order to *actually* upload the file to your Dropbox. Here's how you can do it:

```php
try {
    // Upload the File
    $file = $dropbox->upload($dropboxFile, $backupFilename);
   // File uploaded
   echo $file->getName() . " was successfully uploaded on your Dropbox";
} catch (DropboxClientException $e) {
    echo $e->getMessage();
}
```

**See [Upload and Download Files documentation](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Upload-and-Download-Files#auto-file-upload)**
